In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3,4,"hello"]

In [7]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [8]:
l = [[1,2,3,4] ,[4,5,6,7]]

In [9]:
l

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [10]:
np.array(l)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [11]:
a = np.arange(1,11)

In [12]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
b = np.zeros(6)

In [14]:
b

array([0., 0., 0., 0., 0., 0.])

In [15]:
mat = np.zeros((6,6))

In [16]:
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
o = np.ones(6)

In [18]:
o

array([1., 1., 1., 1., 1., 1.])

In [19]:
O= np.ones((6,6))

In [20]:
O

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
L = np.linspace(1,5,3)

In [22]:
L

array([1., 3., 5.])

In [23]:
np.random.rand(10)

array([0.43590819, 0.91474797, 0.01175647, 0.56565365, 0.14442591,
       0.71652847, 0.70324145, 0.64700967, 0.77370299, 0.78382897])

In [24]:
np.random.randn(10)

array([ 0.52438911,  1.69177856, -0.9962555 , -0.95853944, -1.06836014,
        1.02854895, -1.9246279 , -1.66422273, -1.75158407, -1.22384913])

In [25]:
np.random.randint(6)

3

In [26]:
np.random.randint(10,20,5)

array([15, 15, 10, 11, 14], dtype=int32)

In [27]:
n= np.array([[1,2,3],[3,4,5] ,[7,8,9]])

In [28]:
n

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [30]:
n.size

9

In [31]:

n.shape

(3, 3)

In [34]:
n.min()

np.int64(1)

In [36]:
n.max()

np.int64(9)

In [37]:
n.sum()

np.int64(42)

In [38]:
np.sum(n,axis=0)

array([11, 14, 17])

In [39]:
np.sum(n,axis=1)

array([ 6, 12, 24])

In [40]:
n.mean()

np.float64(4.666666666666667)

In [41]:
n.argmin()

np.int64(0)

In [42]:
n.argmax()

np.int64(8)

In [46]:
arr= np.arange(1,31)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [49]:
arr.resize(6,5)

In [50]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [51]:
ar = np.arange(11,21)

In [52]:
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
ar[9]

np.int64(20)

In [55]:
ar[1:5]

array([12, 13, 14, 15])

In [56]:
ar[:5]

array([11, 12, 13, 14, 15])

In [57]:
ar[3::2]

array([14, 16, 18, 20])

In [58]:
arr= np.arange(1,31).reshape(6,5)

In [59]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [60]:
arr[0]

array([1, 2, 3, 4, 5])

In [61]:
arr[0,0]

np.int64(1)

In [63]:
arr[0,4]

np.int64(5)

In [64]:
slice = arr[0:2,1:3]

In [65]:
slice

array([[2, 3],
       [7, 8]])

In [70]:
slice = arr[3:,3:]

In [71]:
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [72]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [73]:

arr= np.arange(11,21)

In [74]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [75]:
bool_index = arr%2==0

In [76]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [78]:
arr = arr[bool_index]

In [79]:
arr

array([12, 14, 16, 18, 20])

Array operation 

In [83]:
a1 = np.array([1,2,3,5,6,4,5])
a2= np.array([56,85,885,7,4,5,5])

In [84]:
a1+a2

array([ 57,  87, 888,  12,  10,   9,  10])

In [85]:
a1-a2

array([ -55,  -83, -882,   -2,    2,   -1,    0])

a1/a2

In [86]:
a1/a2

array([0.01785714, 0.02352941, 0.00338983, 0.71428571, 1.5       ,
       0.8       , 1.        ])

In [99]:
a= np.arange(1,21)

In [100]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [101]:
a[:5]

array([1, 2, 3, 4, 5])

In [102]:
slice = a[:5]*10

In [103]:
slice

array([10, 20, 30, 40, 50])

In [104]:
a
b =a.copy()




In [105]:
b[0]=99

In [106]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [111]:
A = np.array([[1,2,3],[3,4,5]])
B = np.array([[1,4,5],[5,6,5]])

In [114]:
A.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [115]:
A

array([[1, 2, 3],
       [3, 4, 5]])

In [116]:
B

array([[1, 4, 5],
       [5, 6, 5]])

In [117]:
np.vstack((A,B))

array([[1, 2, 3],
       [3, 4, 5],
       [1, 4, 5],
       [5, 6, 5]])

In [120]:
np.hstack((A,B))

array([[1, 2, 3, 1, 4, 5],
       [3, 4, 5, 5, 6, 5]])

In [121]:
np.column_stack((A,B))

array([[1, 2, 3, 1, 4, 5],
       [3, 4, 5, 5, 6, 5]])

In [122]:
 c= np.arange(16).reshape(4,4) 

In [123]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [124]:
np.split(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Exercises

In [ ]:
s